apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pyreact-{{ENVIRONMENT}}
  labels:
    app: frontend
    environment: {{ENVIRONMENT}}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: frontend
      environment: {{ENVIRONMENT}}
  template:
    metadata:
      labels:
        app: frontend
        environment: {{ENVIRONMENT}}
    spec:
      nodeSelector:
        workload: application
      tolerations:
      - key: workload
        operator: Equal
        value: application
        effect: NoSchedule
      containers:
      - name: frontend
        image: {{ACR_NAME}}.azurecr.io/frontend:{{IMAGE_TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_API_URL
          value: "/api"
        - name: ENVIRONMENT
          value: {{ENVIRONMENT}}
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

