apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: pyreact-{{ENVIRONMENT}}
data:
  # Backend configuration
  CORS_ORIGINS: "*"
  LOG_LEVEL: "INFO"
  API_PREFIX: "/api"
  
  # Frontend configuration
  REACT_APP_VERSION: "1.0.0"
  REACT_APP_ENVIRONMENT: {{ENVIRONMENT}}
