apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: pyreact-{{ENVIRONMENT}}
type: Opaque
data:
  # These would be populated by your CI/CD pipeline
  # Base64 encoded values
  DATABASE_URL: cG9zdGdyZXNxbDovL3BnYWRtaW46cGFzc3dvcmRAbG9jYWxob3N0L3B5cmVhY3RfZGV2  # Example
  REDIS_URL: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OQ==  # Example