version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      # Add your environment variables here
      # - DATABASE_URL=your_database_url
      # - NEXT_PUBLIC_API_URL=your_api_url
    restart: unless-stopped
    # Uncomment if you need to connect to other services
    # networks:
    #   - app-network

# Uncomment if you need a custom network
# networks:
#   app-network:
#     driver: bridge